export const COMMON = {
  SEARCH_DATA: "SEARCH_DATA",
  FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
  FETCH_USERSLIST_SUCCESS: "FETCH_USERSLIST_SUCCESS",
};
